version: "3.7"
services:
  traefik:
    image: traefik:2.2
    command: traefik
    ports:
      # The HTTP port and dashboard
      - "80:80"
      - "8081:8080"
    volumes:
      # Mounting the config file
      - ./traefik-config.toml:/etc/traefik/traefik.toml
      - ./provider.toml:/etc/traefik/provider.toml


