[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[api]
  insecure = true
  dashboard = true

[log]
  level = "DEBUG"
[accessLog]

[entryPoints]
  [entryPoints.http]
    address = ":80"

[providers]
  [providers.file]
    filename = "/etc/traefik/provider.toml"