[global]
  checkNewVersion = true
  sendAnonymousUsage = true
[entryPoints]
  [entryPoints.http]
    address = ":80"
[api]
  insecure = true
  dashboard = true

[file]

[backends]

  [backends.backend1]

    [backends.backend1.servers]
      [backends.backend1.servers.server0]
        url = "http://192.168.178.71:30954/"
        weight = 1


[frontends]

  [frontends.frontend1]
    entryPoints = ["http"]
    backend = "backend1"
    passHostHeader = true
    priority = 42