[global]
  checkNewVersion = true
  sendAnonymousUsage = true
[entryPoints]
  [entryPoints.http]
    address = ":80"
[api]
  insecure = true
  dashboard = true
[log]
  level = "DEBUG"
[frontends]
  [frontends.frontend1]
  backend = "backend1"
  entryPoints = ["http"]
  passHostHeader = true
    [frontends.frontend1.routes.test_1]
    rule = "Host:localhost,192.168.178.71"

[backends]
  [backends.backend1]
    [backends.backend1.servers]
      [backends.backend1.servers.server0]
        url = "http://192.168.178.71:30954/"
        weight = 1
      [backends.backend1.servers.server1]
        url = "http://192.168.178.73:30954/"
        weight = 2
    [backends.backend1.loadBalancer]
      method = "drr"